package com.ismayilov.techapp.dto.response;

public enum StatusCode {
    INVALID_DTO, USER_EXIST, SUCCESS,
    USER_NOT_EXIST, NOT_ACTIVE_ACCOUNT,
    SAME_ACCOUNT_TRANSFER, INVALID_AMOUNT,
    INTERNAL_ERROR, DEBIT_ACCOUNT_INACTIVE, CREDIT_ACCOUNT_INACTIVE,
    INSUFFICIENT_DEBIT_BALANCE, INSUFFICIENT_CREDIT_BALANCE,
    DEBIT_ACCOUNT_NOT_PRESENT, CREDIT_ACCOUNT_NOT_PRESENT
}
